<a href="https://colab.research.google.com/github/merishabh1/Numpy/blob/main/Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [6]:
myarr = np.array(mylist)

In [7]:
type(myarr)

numpy.ndarray

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(1)

array([0.25588087])

In [21]:
np.random.rand(5,3)

array([[0.28946378, 0.03923546, 0.36363896],
       [0.23093954, 0.80557094, 0.39792773],
       [0.78648786, 0.14186021, 0.72742054],
       [0.9070838 , 0.37321887, 0.20477518],
       [0.15665266, 0.16273169, 0.73642016]])

In [22]:
np.random.randn(2,3)

array([[-0.06711404, -2.29191793, -0.90977398],
       [-0.45914325,  0.42660558, -1.67123873]])

In [25]:
np.random.randint(0,101,(4,5))

array([[ 89,   3,  46,  80,  86],
       [ 80,  44,  18,  14,  41],
       [ 51,  43,  34,  30,  54],
       [100,  69,  12,  93,  96]])

In [26]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [28]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [29]:
arr = np.arange(0,25)

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
ranarr = np.random.randint(0,101,10)
ranarr

array([ 1, 87, 29, 37,  1, 63, 59, 20, 32, 75])

In [35]:
ranarr.max()

87

In [36]:
ranarr.argmax()

1

In [37]:
ranarr.dtype

dtype('int64')

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
arr.shape

(25,)

In [40]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
arr.shape

(25,)

(25,)