<a href="https://colab.research.google.com/github/merishabh1/Numpy/blob/main/Numpy_Indexing_and_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]


array([1, 2, 3, 4])

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)

In [11]:
slice_of_arr = arr[0:5]

In [12]:
slice_of_arr[:] = 99

In [13]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [16]:
arr_copy = arr.copy()

In [17]:
arr_copy[:] = 100

In [18]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [19]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [21]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr_2d.shape

(3, 3)

In [24]:
arr_2d[0][1]

10

In [25]:
arr_2d[0,1]

10

In [26]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [27]:
arr = np.arange(1,11)

In [28]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [29]:
bool_arr = arr>4

In [30]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])